#!/usr/bin/env bash
# gen-map.sh — generate docs/MAP.md
#
# Reads:  the filesystem (respects .gitignore)
# Writes: stdout
#
# Generates an annotated directory tree.
# Annotations come from per-directory PURPOSE files or git-tracked top-of-dir markers.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$REPO_ROOT"

NOW="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

# Helper: lookup a generic annotation for a well-known directory name.
# Only includes universally-recognizable conventions. Repo-specific
# annotations should be added to docs/ARCHITECTURE.md by the Bootstrap
# agent — not hardcoded here.
annotate_dir() {
  local d="$1"
  case "$d" in
    apps)             echo "Application(s)";;
    packages)         echo "Shared workspace packages";;
    src)              echo "Source code";;
    lib)              echo "Library code";;
    scripts)          echo "Repo-wide scripts";;
    scripts/llm-docs) echo "docent template tooling";;
    docs)             echo "Repo-level LLM-friendly documentation";;
    examples)         echo "Sample code / example apps";;
    tests|test|__tests__)  echo "Test suites";;
    public)           echo "Static assets served as-is";;
    config)           echo "Configuration";;
    prisma)           echo "Prisma schema + migrations";;
    migrations|db/migrate)  echo "Database migrations";;
    terraform|pulumi|cdk)   echo "Infrastructure-as-code";;
    .agents)          echo "Machine-readable doc inventory (docent)";;
    .github)          echo "GitHub config, workflows, templates";;
    .claude)          echo "Claude Code config";;
    .cursor)          echo "Cursor IDE rules";;
    research)         echo "Research library (docent scout pipeline)";;
    *) echo "";;
  esac
}

cat <<EOF
---
owner: generator
edit_authority: [generator, human]
merge_policy: auto
source: scripts/llm-docs/gen-map.sh
updated: $NOW
hash: pending
generated_hash: pending
---

<!-- AUTO-GENERATED — edit will be overwritten on next sync. See: scripts/llm-docs/gen-map.sh -->

# Repo Map

> **Anchor:** [↑ ARCHITECTURE.md](./ARCHITECTURE.md) · [← AGENTS.md](../AGENTS.md)
> **Purpose:** Annotated directory tree for fast navigation.
> **Source of truth:** the filesystem itself (regenerated by \`gen-map.sh\`).

## Top level

\`\`\`
EOF
echo "$(basename "$REPO_ROOT")/"

# Top-level dirs only
top_dirs=$(find . -maxdepth 1 -mindepth 1 -type d \
  ! -path './node_modules' ! -path './.git' ! -path './.next' ! -path './.turbo' \
  ! -path './.vercel' ! -path './.cache' ! -path './dist' ! -path './build' \
  | sort | sed 's|^\./||')

for d in $top_dirs; do
  ann=$(annotate_dir "$d")
  if [ -n "$ann" ]; then
    printf "├── %-25s %s\n" "$d/" "$ann"
  else
    printf "├── %s/\n" "$d"
  fi
done
echo '```'

echo
echo "## apps/docs/ — the application"
echo
echo '```'
echo "apps/docs/"
find apps/docs -maxdepth 1 -mindepth 1 -type d \
  ! -path '*/node_modules' ! -path '*/.next' ! -path '*/.turbo' \
  | sort | while read -r d; do
  rel=${d#apps/docs/}
  ann=$(annotate_dir "apps/docs/$rel")
  if [ -n "$ann" ]; then
    printf "├── %-15s %s\n" "$rel/" "$ann"
  else
    printf "├── %s/\n" "$rel"
  fi
done
echo '```'

echo
echo "## packages/ — shared libraries"
echo
echo '```'
echo "packages/"
find packages -maxdepth 1 -mindepth 1 -type d \
  ! -path '*/node_modules' \
  | sort | while read -r d; do
  rel=${d#packages/}
  ann=$(annotate_dir "packages/$rel")
  if [ -n "$ann" ]; then
    printf "├── %-25s %s\n" "$rel/" "$ann"
  else
    printf "├── %s/\n" "$rel"
  fi
done
echo '```'

# Statistics
ALL_FILES=$(git ls-files 2>/dev/null | wc -l | tr -d ' ' || echo 0)
TS_FILES=$(git ls-files '*.ts' '*.tsx' 2>/dev/null | wc -l | tr -d ' ' || echo 0)
MDX_FILES=$(git ls-files '*.mdx' '*.md' 2>/dev/null | wc -l | tr -d ' ' || echo 0)

cat <<EOF

## Statistics

| Metric | Count |
|---|---|
| Total tracked files | $ALL_FILES |
| TypeScript files | $TS_FILES |
| Markdown / MDX files | $MDX_FILES |

---

## See also

- [↑ ARCHITECTURE.md](./ARCHITECTURE.md) — system anchor
- [STACK.md](./STACK.md) — what's installed
- [CONVENTIONS.md](./CONVENTIONS.md) — code patterns inside these directories
EOF
